# read env file:
spring.config.import=optional:file:.env[.properties], optional:classpath:metadata.properties

# Generals
spring.application.name=${SPRING_APP_NAME}
server.port=${HOST_PORT}

# Eureka server
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.instance.prefer-ip-address=false
eureka.server.enable-self-preservation=false

management.endpoints.web.exposure.include=health,info
